"""Static specs, aliases, and contracts for the intent router."""

from __future__ import annotations

from zen_claw.agent.intent_router_contracts import IntentToolContract, RetryPolicy


class IntentRouterSpecsMixin:
    _MAX_FORECAST_DAYS = 16
    _CURRENCY_ALIASES = {
        "usd": "USD",
        "us dollar": "USD",
        "dollar": "USD",
        "美元": "USD",
        "美金": "USD",
        "cny": "CNY",
        "rmb": "CNY",
        "renminbi": "CNY",
        "人民币": "CNY",
        "元": "CNY",
        "eur": "EUR",
        "euro": "EUR",
        "欧元": "EUR",
        "jpy": "JPY",
        "yen": "JPY",
        "日元": "JPY",
        "日币": "JPY",
        "gbp": "GBP",
        "pound": "GBP",
        "英镑": "GBP",
        "hkd": "HKD",
        "港币": "HKD",
        "港元": "HKD",
        "cad": "CAD",
        "加元": "CAD",
        "aud": "AUD",
        "澳元": "AUD",
        "sgd": "SGD",
        "新加坡元": "SGD",
        "krw": "KRW",
        "韩元": "KRW",
        "chf": "CHF",
        "瑞士法郎": "CHF",
    }
    _CURRENCY_LABELS = {
        "USD": "美元",
        "CNY": "人民币",
        "EUR": "欧元",
        "JPY": "日元",
        "GBP": "英镑",
        "HKD": "港币",
        "CAD": "加元",
        "AUD": "澳元",
        "SGD": "新加坡元",
        "KRW": "韩元",
        "CHF": "瑞士法郎",
    }
    _TIMEZONE_ALIASES = {
        "北京时间": "Asia/Shanghai",
        "中国时间": "Asia/Shanghai",
        "上海时间": "Asia/Shanghai",
        "上海": "Asia/Shanghai",
        "北京": "Asia/Shanghai",
        "北京时间区": "Asia/Shanghai",
        "utc": "UTC",
        "gmt": "UTC",
        "世界协调时": "UTC",
        "伦敦": "Europe/London",
        "伦敦时间": "Europe/London",
        "东京": "Asia/Tokyo",
        "东京时间": "Asia/Tokyo",
        "首尔": "Asia/Seoul",
        "首尔时间": "Asia/Seoul",
        "新加坡": "Asia/Singapore",
        "新加坡时间": "Asia/Singapore",
        "香港": "Asia/Hong_Kong",
        "香港时间": "Asia/Hong_Kong",
        "纽约": "America/New_York",
        "纽约时间": "America/New_York",
        "洛杉矶": "America/Los_Angeles",
        "洛杉矶时间": "America/Los_Angeles",
        "旧金山": "America/Los_Angeles",
        "旧金山时间": "America/Los_Angeles",
        "西雅图": "America/Los_Angeles",
        "西雅图时间": "America/Los_Angeles",
        "芝加哥": "America/Chicago",
        "芝加哥时间": "America/Chicago",
        "巴黎": "Europe/Paris",
        "巴黎时间": "Europe/Paris",
        "柏林": "Europe/Berlin",
        "柏林时间": "Europe/Berlin",
        "悉尼": "Australia/Sydney",
        "悉尼时间": "Australia/Sydney",
        "纽约市": "America/New_York",
        "tokyo": "Asia/Tokyo",
        "new york": "America/New_York",
        "newyork": "America/New_York",
        "los angeles": "America/Los_Angeles",
        "san francisco": "America/Los_Angeles",
        "seattle": "America/Los_Angeles",
        "chicago": "America/Chicago",
        "london": "Europe/London",
        "paris": "Europe/Paris",
        "berlin": "Europe/Berlin",
        "sydney": "Australia/Sydney",
        "singapore": "Asia/Singapore",
        "hong kong": "Asia/Hong_Kong",
        "seoul": "Asia/Seoul",
    }
    _FALLBACK_FIXED_TIMEZONES = {
        "UTC": (0, "UTC"),
        "Asia/Shanghai": (8, "CST"),
        "Asia/Tokyo": (9, "JST"),
        "Asia/Seoul": (9, "KST"),
        "Asia/Singapore": (8, "SGT"),
        "Asia/Hong_Kong": (8, "HKT"),
    }
    _WEATHER_CONTRACT = IntentToolContract(
        intent_name="weather",
        intent_mode="router_first",
        preferred_tools=["web_fetch"],
        allowed_tools={"web_fetch"},
        denied_tools={"exec", "spawn", "write_file", "edit_file"},
        allow_constrained_replan=True,
        allow_high_risk_escalation=False,
        response_mode="direct",
        failure_mode="runtime_direct",
        fact_payload_schema={
            "type": "object",
            "fields": ["location", "requested_days", "max_supported_days", "reason"],
        },
    )
    _TIME_CONTRACT = IntentToolContract(
        intent_name="time",
        intent_mode="router_first",
        preferred_tools=[],
        allowed_tools=set(),
        denied_tools={"exec", "spawn", "write_file", "edit_file", "web_fetch"},
        allow_constrained_replan=False,
        allow_high_risk_escalation=False,
        response_mode="direct",
        failure_mode="runtime_direct",
    )
    _EXCHANGE_CONTRACT = IntentToolContract(
        intent_name="exchange_rate",
        intent_mode="router_first",
        preferred_tools=["web_fetch"],
        allowed_tools={"web_fetch"},
        denied_tools={"exec", "spawn", "write_file", "edit_file"},
        allow_constrained_replan=True,
        allow_high_risk_escalation=False,
        response_mode="direct",
        failure_mode="runtime_direct",
    )
    _FIXED_SITE_CONTRACT = IntentToolContract(
        intent_name="fixed_site_fetch",
        intent_mode="router_first",
        preferred_tools=["web_fetch"],
        allowed_tools={"web_fetch"},
        denied_tools={"exec", "spawn", "write_file", "edit_file"},
        allow_constrained_replan=True,
        allow_high_risk_escalation=False,
        response_mode="direct",
        failure_mode="runtime_direct",
    )
    _EXEC_CONTRACT = IntentToolContract(
        intent_name="code_exec",
        intent_mode="router_first",
        preferred_tools=[],
        allowed_tools=set(),
        denied_tools={"exec", "spawn", "write_file", "edit_file", "web_fetch"},
        allow_constrained_replan=True,
        allow_high_risk_escalation=True,
        response_mode="llm_assisted",
        failure_mode="runtime_direct",
    )
    _LOW_RISK_FETCH_RETRY = RetryPolicy(max_attempts=2)

    # ── Stock / Crypto price lookup ────────────────────────────────────────────
    _STOCK_ALIASES: dict[str, str] = {
        # Chinese company names → US ticker
        "苹果": "AAPL",
        "微软": "MSFT",
        "谷歌": "GOOGL",
        "亚马逊": "AMZN",
        "特斯拉": "TSLA",
        "英伟达": "NVDA",
        "脸书": "META",
        "meta": "META",
        "奈飞": "NFLX",
        "netflix": "NFLX",
        "台积电": "TSM",
        "阿里巴巴": "BABA",
        "腾讯": "0700.HK",
        "京东": "JD",
    }
    # Map common crypto names/symbols → CoinGecko IDs
    _CRYPTO_IDS: dict[str, str] = {
        "btc": "bitcoin",
        "bitcoin": "bitcoin",
        "比特币": "bitcoin",
        "eth": "ethereum",
        "ethereum": "ethereum",
        "以太坊": "ethereum",
        "ether": "ethereum",
        "sol": "solana",
        "solana": "solana",
        "bnb": "binancecoin",
        "usdt": "tether",
        "xrp": "ripple",
        "ripple": "ripple",
        "doge": "dogecoin",
        "dogecoin": "dogecoin",
        "狗狗币": "dogecoin",
        "ada": "cardano",
        "cardano": "cardano",
        "avax": "avalanche-2",
        "dot": "polkadot",
        "polkadot": "polkadot",
        "matic": "matic-network",
        "polygon": "matic-network",
        "link": "chainlink",
        "chainlink": "chainlink",
        "ltc": "litecoin",
        "litecoin": "litecoin",
    }
    _STOCK_CONTRACT = IntentToolContract(
        intent_name="stock_price",
        intent_mode="router_first",
        preferred_tools=["web_fetch"],
        allowed_tools={"web_fetch"},
        denied_tools={"exec", "spawn", "write_file", "edit_file"},
        allow_constrained_replan=True,
        allow_high_risk_escalation=False,
        response_mode="direct",
        failure_mode="runtime_direct",
    )

    # ── Quick note capture ─────────────────────────────────────────────────────
    _QUICK_NOTE_CONTRACT = IntentToolContract(
        intent_name="quick_note",
        intent_mode="router_first",
        preferred_tools=["write_file"],
        allowed_tools={"write_file"},
        denied_tools={"exec", "spawn", "web_fetch"},
        allow_constrained_replan=False,
        allow_high_risk_escalation=False,
        response_mode="direct",
        failure_mode="runtime_direct",
    )
